import time
import getopt
import sys
from luma.core.interface.serial import spi, noop
from luma.core.render import canvas
from luma.led_matrix.device import max7219


global letter 
global timeOfWait
global rotation
global word

timeOfWait = 1
rotation = 0
word = False
letter = False

if not len(sys.argv[1:]):
	sys.exit(0)
try:
	opts, args = getopt.getopt(sys.argv[1:], "l:t:r:w",  ["letter", "time", "rotation", "word"])
except getopt.GetoptError as err:
	print(err)
	sys.exit(0)


for o, a in opts:
	if o in ("-l"):
		letter = a.upper()
	elif o in ("-t"):
		timeOfWait = float(a)
	elif o in ("-r"):
		rotation = int(a)
	elif o in ("-w")
		word = str(a)


if not word and not letter:
	print("Please specify word or letter!!!")


def show_letter(letter):
	if letter == "A":
		with canvas(device) as draw: #A
			draw.point((7,1), fill="red")
			draw.point((7,2), fill="red")
			draw.point((7,3), fill="red")
			draw.point((7,4), fill="red")
			draw.point((7,5), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((6,3), fill="red")
			draw.point((6,4), fill="red")
			draw.point((6,5), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,2), fill="red")
			draw.point((5,5), fill="red")
			draw.point((5,6), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,2), fill="red")
			draw.point((4,5), fill="red")
			draw.point((4,6), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,2), fill="red")
			draw.point((3,3), fill="red")
			draw.point((3,4), fill="red")
			draw.point((3,5), fill="red")
			draw.point((3,6), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,2), fill="red")
			draw.point((2,3), fill="red")
			draw.point((2,4), fill="red")
			draw.point((2,5), fill="red")
			draw.point((2,6), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,2), fill="red")
			draw.point((1,5), fill="red")
			draw.point((1,6), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
			draw.point((0,5), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "B":
		with canvas(device) as draw: #B
			draw.point((7,1), fill="red")
			draw.point((7,2), fill="red")
			draw.point((7,3), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,4), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,4), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,2), fill="red")
			draw.point((4,3), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,2), fill="red")
			draw.point((3,3), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,4), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,4), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
			draw.point((0,3), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "C":
		with canvas(device) as draw: #C
			draw.point((7,1), fill="red")
			draw.point((7,2), fill="red")
			draw.point((7,3), fill="red")
			draw.point((7,4), fill="red")
			draw.point((7,5), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((6,3), fill="red")
			draw.point((6,4), fill="red")
			draw.point((6,5), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,2), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,2), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,2), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,2), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,2), fill="red")
			draw.point((1,3), fill="red")
			draw.point((1,4), fill="red")
			draw.point((1,5), fill="red")
			draw.point((1,6), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
			draw.point((0,3), fill="red")
			draw.point((0,4), fill="red")
			draw.point((0,5), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "D":
		with canvas(device) as draw: #D
			draw.point((7,1), fill="red")
			draw.point((7,2), fill="red")
			draw.point((7,3), fill="red")
			draw.point((7,4), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((6,3), fill="red")
			draw.point((6,4), fill="red")
			draw.point((6,5), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,5), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,5), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,5), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,5), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,2), fill="red")
			draw.point((1,3), fill="red")
			draw.point((1,4), fill="red")
			draw.point((1,5), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
			draw.point((0,3), fill="red")
			draw.point((0,4), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "E":
		with canvas(device) as draw: #E
			draw.point((7,1), fill="red")
			draw.point((7,2), fill="red")
			draw.point((7,3), fill="red")
			draw.point((7,4), fill="red")
			draw.point((7,5), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((6,3), fill="red")
			draw.point((6,4), fill="red")
			draw.point((6,5), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,2), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,2), fill="red")
			draw.point((4,3), fill="red")
			draw.point((4,4), fill="red")
			draw.point((4,5), fill="red")
			draw.point((4,6), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,2), fill="red")
			draw.point((3,3), fill="red")
			draw.point((3,4), fill="red")
			draw.point((3,5), fill="red")
			draw.point((3,6), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,2), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,2), fill="red")
			draw.point((1,3), fill="red")
			draw.point((1,4), fill="red")
			draw.point((1,5), fill="red")
			draw.point((1,6), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
			draw.point((0,3), fill="red")
			draw.point((0,4), fill="red")
			draw.point((0,5), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "F":
		with canvas(device) as draw: #F
			draw.point((7,1), fill="red")
			draw.point((7,2), fill="red")
			draw.point((7,3), fill="red")
			draw.point((7,4), fill="red")
			draw.point((7,5), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((6,3), fill="red")
			draw.point((6,4), fill="red")
			draw.point((6,5), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,2), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,2), fill="red")
			draw.point((4,3), fill="red")
			draw.point((4,4), fill="red")
			draw.point((4,5), fill="red")
			draw.point((4,6), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,2), fill="red")
			draw.point((3,3), fill="red")
			draw.point((3,4), fill="red")
			draw.point((3,5), fill="red")
			draw.point((3,6), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,2), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,2), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "G":
		with canvas(device) as draw:#g
			draw.point((7,1), fill="red")
			draw.point((7,2), fill="red")
			draw.point((7,3), fill="red")
			draw.point((7,4), fill="red")
			draw.point((7,5), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((5,1), fill="red")
			draw.point((4,1), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,4), fill="red")
			draw.point((3,5), fill="red")
			draw.point((3,6), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,6), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,6), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
			draw.point((0,3), fill="red")
			draw.point((0,4), fill="red")
			draw.point((0,5), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "H":
		with canvas(device) as draw:#h
			draw.point((7,1), fill="red")
			draw.point((7,2), fill="red")
			draw.point((7,5), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((6,5), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,2), fill="red")
			draw.point((5,5), fill="red")
			draw.point((5,6), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,2), fill="red")
			draw.point((4,3), fill="red")
			draw.point((4,4), fill="red")
			draw.point((4,5), fill="red")
			draw.point((4,6), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,2), fill="red")
			draw.point((3,3), fill="red")
			draw.point((3,4), fill="red")
			draw.point((3,5), fill="red")
			draw.point((3,6), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,2), fill="red")
			draw.point((2,5), fill="red")
			draw.point((2,6), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,2), fill="red")
			draw.point((1,5), fill="red")
			draw.point((1,6), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
			draw.point((0,5), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "I":
		with canvas(device) as draw:#i
			draw.point((7,3), fill="red")
			draw.point((7,4), fill="red")
			draw.point((6,3), fill="red")
			draw.point((6,4), fill="red")
			draw.point((5,3), fill="red")
			draw.point((5,4), fill="red")
			draw.point((4,3), fill="red")
			draw.point((4,4), fill="red")
			draw.point((3,3), fill="red")
			draw.point((3,4), fill="red")
			draw.point((2,3), fill="red")
			draw.point((2,4), fill="red")
			draw.point((1,3), fill="red")
			draw.point((1,4), fill="red")
			draw.point((0,3), fill="red")
			draw.point((0,4), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "J":
		with canvas(device) as draw: #j
			draw.point((7,5), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,5), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,5), fill="red")
			draw.point((5,6), fill="red")
			draw.point((4,5), fill="red")
			draw.point((4,6), fill="red")
			draw.point((3,5), fill="red")
			draw.point((3,6), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,2), fill="red")
			draw.point((2,5), fill="red")
			draw.point((2,6), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,2), fill="red")
			draw.point((1,3), fill="red")
			draw.point((1,4), fill="red")
			draw.point((1,5), fill="red")
			draw.point((1,6), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
			draw.point((0,3), fill="red")
			draw.point((0,4), fill="red")
			draw.point((0,5), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "K":
		with canvas(device) as draw: #k
			draw.point((7,1), fill="red")
			draw.point((7,2), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((6,5), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,2), fill="red")
			draw.point((5,3), fill="red")
			draw.point((5,4), fill="red")
			draw.point((5,5), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,2), fill="red")
			draw.point((4,3), fill="red")
			draw.point((4,4), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,2), fill="red")
			draw.point((3,3), fill="red")
			draw.point((3,4), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,2), fill="red")
			draw.point((2,3), fill="red")
			draw.point((2,4), fill="red")
			draw.point((2,5), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,2), fill="red")
			draw.point((1,5), fill="red")
			draw.point((1,6), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "L":
		with canvas(device) as draw: #l
			draw.point((7,1), fill="red")
			draw.point((7,2), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,2), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,2), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,2), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,2), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,2), fill="red")
			draw.point((1,3), fill="red")
			draw.point((1,4), fill="red")
			draw.point((1,5), fill="red")
			draw.point((1,6), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
			draw.point((0,3), fill="red")
			draw.point((0,4), fill="red")
			draw.point((0,5), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "M":
		with canvas(device) as draw: #m
			draw.point((7,1), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((6,5), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,3), fill="red")
			draw.point((5,4), fill="red")
			draw.point((5,6), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,6), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,6), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,6), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,6), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "N":
		with canvas(device) as draw:#n
			draw.point((7,1), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,3), fill="red")
			draw.point((5,6), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,4), fill="red")
			draw.point((4,6), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,4), fill="red")
			draw.point((3,6), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,5), fill="red")
			draw.point((2,6), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,6), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "O":
		with canvas(device) as draw: #o
			draw.point((7,2), fill="red")
			draw.point((7,3), fill="red")
			draw.point((7,4), fill="red")
			draw.point((7,5), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((6,3), fill="red")
			draw.point((6,4), fill="red")
			draw.point((6,5), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,2), fill="red")
			draw.point((5,5), fill="red")
			draw.point((5,6), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,2), fill="red")
			draw.point((4,5), fill="red")
			draw.point((4,6), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,2), fill="red")
			draw.point((3,5), fill="red")
			draw.point((3,6), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,2), fill="red")
			draw.point((2,5), fill="red")
			draw.point((2,6), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,2), fill="red")
			draw.point((1,3), fill="red")
			draw.point((1,4), fill="red")
			draw.point((1,5), fill="red")
			draw.point((1,6), fill="red")
			draw.point((0,2), fill="red")
			draw.point((0,3), fill="red")
			draw.point((0,4), fill="red")
			draw.point((0,5), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "P":
		with canvas(device) as draw: #p
			draw.point((7,1), fill="red")
			draw.point((7,2), fill="red")
			draw.point((7,3), fill="red")
			draw.point((7,4), fill="red")
			draw.point((7,5), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((6,3), fill="red")
			draw.point((6,4), fill="red")
			draw.point((6,5), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,2), fill="red")
			draw.point((5,5), fill="red")
			draw.point((5,6), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,2), fill="red")
			draw.point((4,5), fill="red")
			draw.point((4,6), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,2), fill="red")
			draw.point((3,3), fill="red")
			draw.point((3,4), fill="red")
			draw.point((3,5), fill="red")
			draw.point((3,6), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,2), fill="red")
			draw.point((2,3), fill="red")
			draw.point((2,4), fill="red")
			draw.point((2,5), fill="red")
			draw.point((2,6), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,2), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
		time.sleep(timeOfWait)
			
	elif letter == "Q":
		with canvas(device) as draw:#q
			draw.point((7,2), fill="red")
			draw.point((7,3), fill="red")
			draw.point((7,4), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,5), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,5), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,5), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,5), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,5), fill="red")
			draw.point((1,2), fill="red")
			draw.point((1,3), fill="red")
			draw.point((1,4), fill="red")
			draw.point((1,5), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "R":
		with canvas(device) as draw:#r
			draw.point((7,1), fill="red")
			draw.point((7,2), fill="red")
			draw.point((7,3), fill="red")
			draw.point((7,4), fill="red")
			draw.point((7,5), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((6,3), fill="red")
			draw.point((6,4), fill="red")
			draw.point((6,5), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,2), fill="red")
			draw.point((5,5), fill="red")
			draw.point((5,6), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,2), fill="red")
			draw.point((4,5), fill="red")
			draw.point((4,6), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,2), fill="red")
			draw.point((3,3), fill="red")
			draw.point((3,4), fill="red")
			draw.point((3,5), fill="red")
			draw.point((3,6), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,2), fill="red")
			draw.point((2,3), fill="red")
			draw.point((2,4), fill="red")
			draw.point((2,5), fill="red")
			draw.point((2,6), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,2), fill="red")
			draw.point((1,4), fill="red")
			draw.point((1,5), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
			draw.point((0,5), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "S":
		with canvas(device) as draw:#s
			draw.point((7,1), fill="red")
			draw.point((7,2), fill="red")
			draw.point((7,3), fill="red")
			draw.point((7,4), fill="red")
			draw.point((7,5), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((6,3), fill="red")
			draw.point((6,4), fill="red")
			draw.point((6,5), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,2), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,2), fill="red")
			draw.point((4,3), fill="red")
			draw.point((4,4), fill="red")
			draw.point((4,5), fill="red")
			draw.point((4,6), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,2), fill="red")
			draw.point((3,3), fill="red")
			draw.point((3,4), fill="red")
			draw.point((3,5), fill="red")
			draw.point((3,6), fill="red")
			draw.point((2,5), fill="red")
			draw.point((2,6), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,2), fill="red")
			draw.point((1,3), fill="red")
			draw.point((1,4), fill="red")
			draw.point((1,5), fill="red")
			draw.point((1,6), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
			draw.point((0,3), fill="red")
			draw.point((0,4), fill="red")
			draw.point((0,5), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "T":
		with canvas(device) as draw:#t 
			draw.point((7,1), fill="red")
			draw.point((7,2), fill="red")
			draw.point((7,3), fill="red")
			draw.point((7,4), fill="red")
			draw.point((7,5), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((6,3), fill="red")
			draw.point((6,4), fill="red")
			draw.point((6,5), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,3), fill="red")
			draw.point((5,4), fill="red")
			draw.point((4,3), fill="red")
			draw.point((4,4), fill="red")
			draw.point((3,3), fill="red")
			draw.point((3,4), fill="red")
			draw.point((2,3), fill="red")
			draw.point((2,4), fill="red")
			draw.point((1,3), fill="red")
			draw.point((1,4), fill="red")
			draw.point((0,3), fill="red")
			draw.point((0,4), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "U":
		with canvas(device) as draw:#u
			draw.point((7,1), fill="red")
			draw.point((7,2), fill="red")
			draw.point((7,5), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((6,5), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,2), fill="red")
			draw.point((5,5), fill="red")
			draw.point((5,6), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,2), fill="red")
			draw.point((4,5), fill="red")
			draw.point((4,6), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,2), fill="red")
			draw.point((3,5), fill="red")
			draw.point((3,6), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,2), fill="red")
			draw.point((2,5), fill="red")
			draw.point((2,6), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,2), fill="red")
			draw.point((1,3), fill="red")
			draw.point((1,4), fill="red")
			draw.point((1,5), fill="red")
			draw.point((1,6), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
			draw.point((0,3), fill="red")
			draw.point((0,4), fill="red")
			draw.point((0,5), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "V":
		with canvas(device) as draw:#v
			draw.point((7,1), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,6), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,6), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,6), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,2), fill="red")
			draw.point((2,5), fill="red")
			draw.point((2,6), fill="red")
			draw.point((1,2), fill="red")
			draw.point((1,3), fill="red")
			draw.point((1,4), fill="red")
			draw.point((1,5), fill="red")
			draw.point((0,3), fill="red")
			draw.point((0,4), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "W":
		with canvas(device) as draw:#w
			draw.point((7,1), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,6), fill="red")
			draw.point((4,1), fill="red")
			draw.point((4,6), fill="red")
			draw.point((3,1), fill="red")
			draw.point((3,6), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,3), fill="red")
			draw.point((2,4), fill="red")
			draw.point((2,6), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,2), fill="red")
			draw.point((1,3), fill="red")
			draw.point((1,4), fill="red")
			draw.point((1,5), fill="red")
			draw.point((1,6), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
			draw.point((0,5), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "X":
		with canvas(device) as draw:#x
			draw.point((7,1), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,2), fill="red")
			draw.point((6,5), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,2), fill="red")
			draw.point((5,3), fill="red")
			draw.point((5,4), fill="red")
			draw.point((5,5), fill="red")
			draw.point((4,3), fill="red")
			draw.point((4,4), fill="red")
			draw.point((3,3), fill="red")
			draw.point((3,4), fill="red")
			draw.point((2,2), fill="red")
			draw.point((2,3), fill="red")
			draw.point((2,4), fill="red")
			draw.point((2,5), fill="red")
			draw.point((1,1), fill="red")
			draw.point((1,2), fill="red")
			draw.point((1,5), fill="red")
			draw.point((1,6), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "Y":
		with canvas(device) as draw:#y
			draw.point((7,1), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,1), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,1), fill="red")
			draw.point((5,2), fill="red")
			draw.point((5,5), fill="red")
			draw.point((5,6), fill="red")
			draw.point((4,2), fill="red")
			draw.point((4,3), fill="red")
			draw.point((4,4), fill="red")
			draw.point((4,5), fill="red")
			draw.point((3,3), fill="red")
			draw.point((3,4), fill="red")
			draw.point((2,3), fill="red")
			draw.point((2,4), fill="red")
			draw.point((1,3), fill="red")
			draw.point((1,4), fill="red")
			draw.point((0,3), fill="red")
			draw.point((0,4), fill="red")
		time.sleep(timeOfWait)
		
	elif letter == "Z":
		with canvas(device) as draw:#z
			draw.point((7,1), fill="red")
			draw.point((7,2), fill="red")
			draw.point((7,3), fill="red")
			draw.point((7,4), fill="red")
			draw.point((7,5), fill="red")
			draw.point((7,6), fill="red")
			draw.point((6,5), fill="red")
			draw.point((6,6), fill="red")
			draw.point((5,4), fill="red")
			draw.point((5,5), fill="red")
			draw.point((4,3), fill="red")
			draw.point((4,4), fill="red")
			draw.point((3,2), fill="red")
			draw.point((3,3), fill="red")
			draw.point((2,1), fill="red")
			draw.point((2,2), fill="red")
			draw.point((1,1), fill="red")
			draw.point((0,1), fill="red")
			draw.point((0,2), fill="red")
			draw.point((0,3), fill="red")
			draw.point((0,4), fill="red")
			draw.point((0,5), fill="red")
			draw.point((0,6), fill="red")
		time.sleep(timeOfWait)
	else 


serial = spi(port=0, device=0, gpio=noop())
device = max7219(serial, rotate=rotation)


if not word:
	show_letter(letter)
elif word:
	for i in range(len(word)):
		if word[i] > 'z' or = word[i] < 'A':
			time.sleep(timeOfWait)
		elif word[i] != " ":
			show_letter(word[i])
		elif word[i] == " ":
			time.sleep(timeOfWait)
